##LE IMMAGINI SI TROVANO NELLA CARTELLA ""IMAGES""

##PER L'EXERCISE1 ERA RICHIESTO DI SALVARE LE IMMAGINI IN QUELLA CARTELLA

##HO REALIZZATO LA FERRARI MONDIAL QUATTROVALVOLE, UN AUTO DA CORSA DI CIRCA 30 ANNI FA.